### PR TITLE
Update docs

### PR DESCRIPTION
**Pull request by pasuder**
Simple updates

### CODE REVIEW

**Comment by pasuder** [comment]
@mkasztelnik what would you like to see more in [`README.md`](https://github.com/dice-cyfronet/migratio/blob/task_update_docs/README.md)?

**Comment by mkasztelnik** [comment]
For sure description about the tool. What is does, what is the added value.

**Comment by paoolo** [comment]
It is described in the first sentence of README.md. Do you suggest to add more information?

**Comment by pasuder** [comment]
It is described in the first sentence of README.md. Do you suggest to add more information?

@dice-cyfronet/atmo-dev-team what would you like to see more in [`README.md`](https://github.com/dice-cyfronet/migratio/blob/task_update_docs/README.md)?

**Comment by mkasztelnik** [comment]
looks good :+1:

**Comment by pasuder** [comment]
@nowakowski could you perform the proofreading process?

**Comment by pasuder** [comment]
@nowakowski would like to read and make some amends?

**Comment by pasuder** [comment]
As @mkasztelnik mentioned in #8 added diagrams to [`README.md`](https://github.com/dice-cyfronet/migratio/blob/task_update_docs/README.md#flow)

**Comment by nowakowski** [comment]
@paoolo I fear "make amends" doesn't mean what you think it means. ;)

**Comment by nowakowski** [comment]
Proofreading done, btw.

**Comment by pasuder** [comment]
@nowakowski "make amends" great... :smile: I guees that there are special powers to "make amends". Gracias!

**Comment by pasuder** [comment]
Updated diagrams in _Flow_ section.

**Pull request merged**
